name: CI Pipeline
run-name: ${{ github.actor }} запустил CI Pipeline 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
        if: always()
      - name: build storybook
        run: npm run build:storybook
        if: always()
      - name: unit test
        run: npm run test:unit
        if: always()
      - name: stylelint check
        run: npm run scss:check
        if: always()
      - name: eslint check
        run: npm run eslint:check
